version: "3.4"
services:
  postgres:
    image: postgres:15.1
    build:
      context: postgres
    environment:
      POSTGRES_DB: chronos
      POSTGRES_USER: chronos
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
